[2024-11-01T01:09:50.679+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T01:09:50.690+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.insert_data manual__2024-11-01T01:09:45.608245+00:00 [queued]>
[2024-11-01T01:09:50.697+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.insert_data manual__2024-11-01T01:09:45.608245+00:00 [queued]>
[2024-11-01T01:09:50.698+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-01T01:09:50.709+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresFileOperator): insert_data> on 2024-11-01 01:09:45.608245+00:00
[2024-11-01T01:09:50.714+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-01T01:09:50.715+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2024-11-01T01:09:50.716+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'insert_data', 'manual__2024-11-01T01:09:45.608245+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/Etl_weather.py', '--cfg-path', '/tmp/tmpbikf9ax_']
[2024-11-01T01:09:50.717+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask insert_data
[2024-11-01T01:09:50.750+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.insert_data manual__2024-11-01T01:09:45.608245+00:00 [running]> on host 915ee6de4e26
[2024-11-01T01:09:50.807+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T01:09:45.608245+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T01:09:45.608245+00:00'
[2024-11-01T01:09:50.809+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T01:09:50.819+0000] {postgres.py:191} INFO - Running copy expert: COPY weather_medellin FROM STDIN, filename: /opt/***/tmp/weather_data.tsv
[2024-11-01T01:09:50.828+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-01T01:09:50.866+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/postgres_file_operator.py", line 20, in execute
    self.writeinDb()
  File "/opt/airflow/plugins/operators/postgres_file_operator.py", line 25, in writeinDb
    self.postgres_hook.bulk_load(self.config.get('table_name'), '/opt/airflow/tmp/weather_data.tsv')
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 211, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 197, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "temp"
CONTEXT:  COPY weather_medellin, line 1, column temp: "temp"

[2024-11-01T01:09:50.876+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=insert_data, run_id=manual__2024-11-01T01:09:45.608245+00:00, execution_date=20241101T010945, start_date=20241101T010950, end_date=20241101T010950
[2024-11-01T01:09:50.885+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T01:09:50.886+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task insert_data (invalid input syntax for type double precision: "temp"
CONTEXT:  COPY weather_medellin, line 1, column temp: "temp"
; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/postgres_file_operator.py", line 20, in execute
    self.writeinDb()
  File "/opt/airflow/plugins/operators/postgres_file_operator.py", line 25, in writeinDb
    self.postgres_hook.bulk_load(self.config.get('table_name'), '/opt/airflow/tmp/weather_data.tsv')
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 211, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 197, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "temp"
CONTEXT:  COPY weather_medellin, line 1, column temp: "temp"

[2024-11-01T01:09:50.931+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-01T01:09:50.946+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T01:09:50.949+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
