[2024-10-31T02:09:04.371+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T02:09:04.500+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.extract_data manual__2024-10-31T02:09:01.852271+00:00 [queued]>
[2024-10-31T02:09:04.507+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.extract_data manual__2024-10-31T02:09:01.852271+00:00 [queued]>
[2024-10-31T02:09:04.509+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-31T02:09:04.520+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract_data> on 2024-10-31 02:09:01.852271+00:00
[2024-10-31T02:09:04.524+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=148) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-31T02:09:04.526+0000] {standard_task_runner.py:72} INFO - Started process 150 to run task
[2024-10-31T02:09:04.526+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'extract_data', 'manual__2024-10-31T02:09:01.852271+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/Etl_weather.py', '--cfg-path', '/tmp/tmpsrx3mj86']
[2024-10-31T02:09:04.527+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask extract_data
[2024-10-31T02:09:04.560+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.extract_data manual__2024-10-31T02:09:01.852271+00:00 [running]> on host 9e0dea6e3339
[2024-10-31T02:09:04.620+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='milo0@gmail.com' AIRFLOW_CTX_DAG_OWNER='milo' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T02:09:01.852271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-31T02:09:01.852271+00:00'
[2024-10-31T02:09:04.621+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T02:09:04.649+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-31T02:09:04.650+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/plugins/tmp/extract_data_api.py']
[2024-10-31T02:09:04.657+0000] {subprocess.py:86} INFO - Output:
[2024-10-31T02:09:05.935+0000] {subprocess.py:93} INFO - {'coord': {'lon': -75.5636, 'lat': 6.2518}, 'weather': [{'id': 300, 'main': 'Drizzle', 'description': 'light intensity drizzle', 'icon': '09n'}], 'base': 'stations', 'main': {'temp': 18.51, 'feels_like': 18.98, 'temp_min': 18.18, 'temp_max': 19.08, 'pressure': 1016, 'humidity': 98, 'sea_level': 1016, 'grnd_level': 807}, 'visibility': 10000, 'wind': {'speed': 8.05, 'deg': 130, 'gust': 0}, 'clouds': {'all': 75}, 'dt': 1730340322, 'sys': {'type': 2, 'id': 2084700, 'country': 'CO', 'sunrise': 1730285317, 'sunset': 1730328180}, 'timezone': -18000, 'id': 3674962, 'name': 'Medell√≠n', 'cod': 200}
[2024-10-31T02:09:05.935+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-31T02:09:05.936+0000] {subprocess.py:93} INFO -   File "/opt/***/plugins/tmp/extract_data_api.py", line 55, in <module>
[2024-10-31T02:09:05.938+0000] {subprocess.py:93} INFO -     extract_weather_data()
[2024-10-31T02:09:05.938+0000] {subprocess.py:93} INFO -   File "/opt/***/plugins/tmp/extract_data_api.py", line 43, in extract_weather_data
[2024-10-31T02:09:05.940+0000] {subprocess.py:93} INFO -     df.to_csv("C:/Users/USUARIO/Desktop/weather_etl/plugins/tmp/weather_data.tsv", sep='\t', index=False, mode='w')
[2024-10-31T02:09:05.941+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
[2024-10-31T02:09:05.941+0000] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2024-10-31T02:09:05.942+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31T02:09:05.942+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
[2024-10-31T02:09:05.943+0000] {subprocess.py:93} INFO -     csv_formatter.save()
[2024-10-31T02:09:05.943+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
[2024-10-31T02:09:05.944+0000] {subprocess.py:93} INFO -     with get_handle(
[2024-10-31T02:09:05.945+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^
[2024-10-31T02:09:05.946+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
[2024-10-31T02:09:05.946+0000] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2024-10-31T02:09:05.947+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
[2024-10-31T02:09:05.947+0000] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2024-10-31T02:09:05.948+0000] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'C:/Users/USUARIO/Desktop/weather_etl/plugins/tmp'
[2024-10-31T02:09:06.009+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-31T02:09:06.021+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-31T02:09:06.030+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=extract_data, run_id=manual__2024-10-31T02:09:01.852271+00:00, execution_date=20241031T020901, start_date=20241031T020904, end_date=20241031T020906
[2024-10-31T02:09:06.049+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T02:09:06.050+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task extract_data (Bash command failed. The command returned a non-zero exit code 1.; 150)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-31T02:09:06.068+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T02:09:06.076+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-10-31T02:09:06.085+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T02:09:06.087+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
